"""
Teacher labeling pipeline for self-bootstrapping.

Takes synthetic behaviors generated by behavior_generator, runs them through
the decision pipeline (decide_for_event) so System 2 produces teacher labels.
Feedback is automatically collected by ExperienceCollector to hard_examples.jsonl.

Progress is saved to a checkpoint file so labeling can resume after interruption.

Usage:
    # With LLM teacher (high quality)
    python scripts/run_teacher_labeling.py

    # Without LLM (rule-based fallback, fast/cheap)
    python scripts/run_teacher_labeling.py --no-llm

    # Resume automatically from last checkpoint
    python scripts/run_teacher_labeling.py --resume

    # Custom paths
    python scripts/run_teacher_labeling.py --input data/synthetic/generated_behaviors.jsonl
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from guardian_policy_agent.config import load_config
from guardian_policy_agent.db.session import init_engine, get_session
from guardian_policy_agent.db.models import MonitorEvent
from guardian_policy_agent.service.decider import decide_for_event
from guardian_policy_agent.tools.behavior_generator import load_behaviors

PROGRESS_FILE = "data/synthetic/labeling_progress.json"


def _load_progress() -> dict:
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE, "r") as f:
            return json.load(f)
    return {"completed": 0, "labeled": 0, "skipped": 0, "errors": 0}


def _save_progress(progress: dict):
    os.makedirs(os.path.dirname(PROGRESS_FILE), exist_ok=True)
    with open(PROGRESS_FILE, "w") as f:
        json.dump(progress, f)


def parse_args():
    p = argparse.ArgumentParser(description="Run teacher labeling on synthetic behaviors")
    p.add_argument("--input", default="data/synthetic/generated_behaviors.jsonl",
                   help="Path to generated behaviors JSONL")
    p.add_argument("--config", default=None)
    p.add_argument("--no-llm", action="store_true", help="Use rule-based fallback instead of LLM")
    p.add_argument("--delay", type=float, default=0.1, help="Delay between LLM calls in seconds")
    p.add_argument("--offset", type=int, default=0, help="Skip first N behaviors (manual override)")
    p.add_argument("--resume", action="store_true", help="Resume from last saved progress")
    p.add_argument("--limit", type=int, default=0, help="Max behaviors to process (0=all)")
    return p.parse_args()


def run_labeling(args):
    use_llm = not args.no_llm

    # Load synthetic behaviors
    behaviors = load_behaviors(args.input)
    total = len(behaviors)
    print(f"[TeacherLabel] Loaded {total} synthetic behaviors from {args.input}")

    # Determine starting offset
    if args.resume:
        progress = _load_progress()
        offset = progress["completed"]
        print(f"[TeacherLabel] Resuming from index {offset} "
              f"(labeled={progress['labeled']}, errors={progress['errors']})")
    elif args.offset > 0:
        offset = args.offset
        progress = {"completed": offset, "labeled": 0, "skipped": 0, "errors": 0}
    else:
        offset = 0
        progress = {"completed": 0, "labeled": 0, "skipped": 0, "errors": 0}

    remaining = behaviors[offset:]
    if args.limit > 0:
        remaining = remaining[:args.limit]

    print(f"[TeacherLabel] Processing {len(remaining)} behaviors (offset={offset}, use_llm={use_llm})")

    # Init DB
    cfg = load_config(args.config)
    init_engine(cfg.db_url, cfg.echo_sql)

    with get_session() as ses:
        for i, item in enumerate(remaining):
            global_idx = offset + i
            beh = item["behavior"]
            domain = item.get("domain", beh.get("domain"))

            try:
                # Insert transient MonitorEvent
                ev = MonitorEvent(
                    user_id="user:bootstrap",
                    platform=beh.get("platform", "web"),
                    domain=domain,
                    action_type=beh.get("action_type", "synthetic_bootstrap"),
                    data_categories=beh.get("data_categories", []),
                    actions=beh.get("actions", []),
                    purposes=beh.get("purposes", []),
                    recipients=beh.get("recipients", []),
                    event_metadata={"bootstrap": True, "generation_type": item.get("generation_type")},
                )
                ses.add(ev)
                ses.flush()
                event_id = ev.id

                # Run decision pipeline
                result = decide_for_event(ses, event_id, use_llm=use_llm)
                system_used = result.get("system_used", "")

                # Clean up transient event
                ses.delete(ev)
                ses.commit()

                progress["labeled"] += 1

                # Rate limiting for LLM calls
                if use_llm and system_used == "llm_agent":
                    time.sleep(args.delay)

            except Exception as e:
                progress["errors"] += 1
                print(f"[TeacherLabel] Error on item {global_idx}: {e}")
                ses.rollback()

            # Update progress and save periodically
            progress["completed"] = global_idx + 1
            if (i + 1) % 10 == 0:
                _save_progress(progress)
                print(f"[TeacherLabel] {global_idx+1}/{total} | "
                      f"labeled={progress['labeled']} errors={progress['errors']} "
                      f"last_decision={result.get('decision', '?')} system={result.get('system_used', '?')}")

    # Final save
    _save_progress(progress)
    print(f"\n[TeacherLabel] Done. {progress}")
    return progress


if __name__ == "__main__":
    args = parse_args()
    run_labeling(args)
